name: Test and Pages
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm test
    - run: pnpm build
    - uses: actions/upload-pages-artifact@v3
      id: deployment
      with:
        path: dist/
  pages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/deploy-pages@v4
